# DINO-setup.yaml

mesh_mask: mesh_mask.nc

restart_files: 'restart'

output_variables:
  temperature: grid_T_3D.nc
  salinity: grid_T_3D.nc
  density: grid_T_3D.nc
  ssh: grid_T_2D.nc
  velocity_u: grid_U_3D.nc
  velocity_v: grid_V_3D.nc
