# DINO-setup.yaml
# should hold true for all DINO runs.

mesh_mask: mesh_mask.nc

restart_files: 'restart'  # optional # density and all variables

output_file_defaults: DINO_combined.nc  # if used in future

output_variables:
  temperature: DINO_1y_grid_T.nc
  salinity: DINO_1y_grid_T.nc
  density: DINO_1y_grid_T.nc
  ssh: DINO_1m_To_1y_grid_T.nc
  velocity_zonal: DINO_1y_grid_U.nc
  velocity_meridional: DINO_1y_grid_V.nc
  velocity_vertical: DINO_1y_grid_W.nc
