# DINO-setup.yaml

mesh_mask: mesh_mask.nc

restart_files: 'restart'

output_variables:
  temperature:
    file: grid_T_3D.nc
    var: toce
  salinity:
    file: grid_T_3D.nc
    var: soce
  density:
    file: grid_T_3D.nc
    var: rhop
  ssh:
    file: grid_T_2D.nc
    var: ssh
  velocity_u:
    file: grid_U_3D.nc
    var: uoce
  velocity_v:
    file: grid_V_3D.nc
    var: voce

variable_map:
  temperature: [tn]
  velocity_u: [un]
  velocity_v: [vn]
  depth: [nav_lev, deptht, depthu, depthv]
  ssh: [sshn]
  salinity: [sn]
  density: [rhop]
