# DINO-setup.yaml
# should hold true for all DINO runs.

mesh_mask: mesh_mask.nc

restart_files: 'restart'  # optional # density and all variables

output_file_defaults: DINO_combined.nc  # if used in future

# overrides defaults
output_variables:
  T: DINO_1y_grid_T.nc
  T_sampled: DINO_1m_To_1y_grid_T.nc
  u: DINO_1y_grid_U.nc
  v: DINO_1y_grid_V.nc
  w: DINO_1y_grid_W.nc

# variable mapping here?
