name: StaticAnalysis
on:
  # Triggers the workflow on pushes to the "main" branch, i.e., PR merges
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  formatting:
    runs-on: ubuntu-latest
    name: Code Formatting and Linting Check
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Ruff for code formatting check
        uses: astral-sh/ruff-action@v3
        with:
          version: 0.11.7
          args: "format --check --diff"

      - name: Run Ruff for linting check
        uses: astral-sh/ruff-action@v3
        with:
          version: 0.11.7
          args: "check"
